### ISSUE TITLE
Does this plugin support importing URDF file to blender?

### ISSUE THREAD

**Issue by Guptajakala** [dfki-ric/phobos#166]
From the surface I can only infer that it supports exporting URDF file once created in blender. Does it do the opposite?

**Comment by AlCap23** [comment]
Yes, you can import urdf files into phobos.

![phobos_import](https://user-images.githubusercontent.com/20998300/47548295-e62d0800-d8f8-11e8-8acb-f0a613d13430.png)

We also support a crude sdf import, which is still work in progress due to the extensive modularity and parametrization of the sdf format.
