### ISSUE TITLE
Naming problem for automatically created/imported objects 

### ISSUE THREAD

**Issue by bosforox** [dfki-ric/phobos#213]
**Describe the bug**
With Blender-phobos co-work, strange naming problems occur when objects are created or imported with same names. This issue causes some problems for further steps in the creation of a composite model(Q-Rock atomic model import). If a name already exists in Blender, a new object with the same name is created with a subfix of .00x, which in a recursion can lead to a chain of possible subfixes like obj_name.001.001.001.001. Maybe the reuse of dots can be avoided or the names can be taken either from parent objects or from prefix (link_.. , visual_... etc). 

@2maz

**Comment by malter** [comment]
This is not really a bug since in Blender the object name is the unique identifier and blender does this name handling on purpose. Normally, Blender identifies .00x and uses .00[x+1] as new name instead of creating chains.
Recursive model imports are not part of Phobos either.
So, what can Phobos do for you to improve your application?

**Comment by hwiedDFKI** [comment]
I consider this as solved, due to inactivity
