### ISSUE TITLE
Incorrect interials created when creating interials for individual parts 

### ISSUE THREAD

**Issue by airsimdevdd** [dfki-ric/phobos#236]
when I'm giving individual mass to individual links the interials are generated wrong

**Comment by malter** [comment]
Hey, I think the inertials can't be calculated correctly based on the links since links have no extend. I normally set a mass to the geometry objects like the collisions or visuals and then use the Phobos operator `create inertials`. There you can select to derive the inertials from the visuals, collisions, or both.

**Comment by hwiedDFKI** [comment]
I consider this as solved, by the explanation of @malter
