### ISSUE TITLE
Trouble constructing links, simple video

### ISSUE THREAD

**Issue by codenotes** [dfki-ric/phobos#3]
I am excited by your tool, have been looking for something like this for some time to model robots.  While I do have it installed successfully, I have to confess I am having some trouble following the tutorials as it applies to creating simple links.    I get URDF exports that are garbage where my links do not reflect a hierarchy.   It may be my lack of familiarity with blender or I am not understanding how to use "create links" correctly...

Can I request a very very simple video on youtube demonstrating the creation and treatment of a super-simple URDF structure?  Just take two cubes, make them links, and put a joint between them. And export.  It would be enormously helpful to see the steps and sequence.  A 2 minute video can take the place of many documentation pages.

Sincere thanks...

**Comment by alextoind** [comment]
Any news about this?

I've already have a look at the wiki, but I miss something especially in the [Kinematic Skeleton tutorial](https://github.com/rock-simulation/phobos/wiki/Kinematic%20Skeleton). As said by @codenotes a very simple video could help a lot: probably because of my lacks in Blender, I don't get the proper way to obtain the [complete kinematic scheme](https://github.com/rock-simulation/phobos/wiki/img/tutorials/basicmodelling/testwalker_create_links_full_options.png) from the [visual one](https://github.com/rock-simulation/phobos/wiki/img/tutorials/basicmodelling/testwalker_object_tree.png).

I'm going to read again the wiki and watch some videos about armatures and bones in Blender, and I hope to get my URDF in a day or two. However, a 5 minute videos could help a lot.

Anyway, thanks for the great tool!

**Comment by kavonszadkowski** [comment]
Sorry for the late reply, Phobos is currently a one-man part-time operation...I agree that the tutorial you refer to is far from comprehensive. I'll try to get it fixed in the coming days.

**Comment by alextoind** [comment]
Don't worry for me: I've quite understood everything of Phobos, I think.

And I have to thank you very much for this great project which will surely save me much time for the next time.

**Comment by Amudtogal** [comment]
We will have the videos released soon. I will close this for now.
