### ISSUE TITLE
AttributeError: module 'bgl' has no attribute 'glBegin'

### ISSUE THREAD

**Issue by reinzler** [dfki-ric/phobos#342]
AttributeError: module 'bgl' has no attribute 'glBegin'

**To Reproduce**
![Screenshot from 2024-01-23 17-08-15](https://github.com/dfki-ric/phobos/assets/109457976/7aad8406-39c9-47d2-b7d8-89d6cc4fba0b)

1. Blender 3.6.8
2. Phobos 2.0.0
3. Terminal output during the process of export model to urdf

**Comment by AlpenAalAlex** [comment]
@reinzler Please take a look at my PR and see if this fixes your error

**Comment by reinzler** [comment]
> @reinzler Please take a look at my PR and see if this fixes your error

Hi, thanks, now I have such error:
[20240209_16:19:01] ERROR No properly defined models to export
![image](https://github.com/dfki-ric/phobos/assets/109457976/f6b8c079-f050-439d-9e17-abe9162843d0)

**Comment by hwiedPro** [comment]
@reinzler Thanks for reporting the issue and testing. This issue seems to be resolved.

To help with your other problem, we could need some more information. Have you defined the root link by giving a name to your model?
Can you share your model or a screenshot? Please also consider the basic modelling walkthrough in the wiki to check if you have done everything that's necessary.

**Comment by reinzler** [comment]
> @reinzler Thanks for reporting the issue and testing. This issue seems to be resolved.
> 
> To help with your other problem, we could need some more information. Have you defined the root link by giving a name to your model? Can you share your model or a screenshot? Please also consider the basic modelling walkthrough in the wiki to check if you have done everything that's necessary.

Hi, sorry for a long time reply, I can share my stl models, not a problem, will it be helpful?
